"""
auto_doc_generator.py — Mermaid & OpenAPI Compiler
==================================================

IBM Bob 2.0 Hackathon · /services/orchestrator/

Zero-effort professional documentation: this script introspects the running
FastAPI application and its Pydantic schemas, then compiles a polished
``ARCHITECTURE.md`` at the repository root — including Mermaid.js diagrams
that GitHub renders natively.

What it generates
-----------------
1. **System overview Mermaid flowchart** — derived from the event-bus topic
   lifecycle (``Topic`` enum), so the diagram can never drift from the code.
2. **Multi-agent consensus loop diagram** — the debate/veto flow.
3. **API route table** — every FastAPI route, method, auth requirement and
   response model, read live from ``main.app``.
4. **Pydantic schema tables** — every request/response/domain model with
   field names, types and required markers, read live from the model classes.
5. **Subsystem registry** — module inventory with one-line responsibilities.

Usage
-----
    python auto_doc_generator.py                 # writes ../ARCHITECTURE.md
    python auto_doc_generator.py --check         # exit 1 if ARCHITECTURE.md is stale (CI gate)

Run it after any route or schema change; wire ``--check`` into CI so the docs
can never silently rot.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Type

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pydantic import BaseModel  # noqa: E402

import main  # noqa: E402  — the live FastAPI app under documentation
from master_event_bus import Topic  # noqa: E402
from multi_agent_consensus import PERSONAS  # noqa: E402
from vector_cve_db import CVEItem, CVEQueryResult  # noqa: E402
from self_healing_loop import HealAttempt, HealResult, SandboxResult, TracebackInfo  # noqa: E402
from roi_calculator import ROIBreakdownItem, ROISummary  # noqa: E402
from cross_language_parser import PolyglotFinding  # noqa: E402
from enterprise_auth import EnterpriseUser, TokenResponse  # noqa: E402

# ---------------------------------------------------------------------------
# Output location: repo root (one level above services/orchestrator/)
# ---------------------------------------------------------------------------

DEFAULT_OUTPUT = Path(__file__).resolve().parents[2] / "ARCHITECTURE.md"

GENERATED_BANNER = (
    "<!-- GENERATED BY services/orchestrator/auto_doc_generator.py — "
    "DO NOT EDIT BY HAND. Regenerate: python auto_doc_generator.py -->"
)


# ---------------------------------------------------------------------------
# Route introspection
# ---------------------------------------------------------------------------

#: Routes that require a JWT (annotated by hand — auth is enforced via
#: Depends(), which is not visible in the route signature cheaply).
_PROTECTED_PATHS = {"/api/v1/modernize"}


def collect_routes() -> List[Dict[str, str]]:
    """Read every registered route from the live FastAPI app."""
    rows: List[Dict[str, str]] = []
    for route in main.app.routes:
        path = getattr(route, "path", None)
        methods = getattr(route, "methods", None)
        if not path or not methods:
            continue  # mounts / websocket internals
        response_model = getattr(route, "response_model", None)
        rows.append({
            "path": path,
            "methods": ", ".join(sorted(m for m in methods if m != "HEAD")),
            "name": getattr(route, "name", ""),
            "auth": "🔒 JWT (`modernizer` role)" if path in _PROTECTED_PATHS else "public",
            "response": response_model.__name__ if response_model else "—",
            "summary": (getattr(route, "summary", None) or "").strip(),
        })
    rows.sort(key=lambda r: r["path"])
    return rows


# ---------------------------------------------------------------------------
# Schema introspection
# ---------------------------------------------------------------------------

#: Models documented in the generated file, grouped by owning subsystem.
SCHEMA_REGISTRY: Dict[str, List[Type[BaseModel]]] = {
    "Orchestrator API (main.py)": [
        main.ModernizationRequest, main.VulnerabilityItem,
        main.RefactorResult, main.ModernizationResponse,
    ],
    "RAG Security Engine (vector_cve_db.py)": [CVEItem, CVEQueryResult],
    "Self-Healing Engine (self_healing_loop.py)": [SandboxResult, TracebackInfo, HealAttempt, HealResult],
    "Business Value Engine (roi_calculator.py)": [ROIBreakdownItem, ROISummary],
    "Polyglot Parser (cross_language_parser.py)": [PolyglotFinding],
    "Zero-Trust Auth (enterprise_auth.py)": [TokenResponse, EnterpriseUser],
}


def _field_type_str(field: Any) -> str:
    """Render a pydantic field's annotation compactly (``str``, not ``<class 'str'>``)."""
    annotation = getattr(field, "annotation", None)
    if isinstance(annotation, type):
        return annotation.__name__
    text = str(annotation).replace("typing.", "")
    # Drop module prefixes from class references inside generics.
    text = re.sub(r"<class '([\w\.]+)'>", lambda m: m.group(1).split(".")[-1], text)
    text = re.sub(r"<enum '([\w\.]+)'>", lambda m: m.group(1).split(".")[-1], text)
    for module in ("main.", "vector_cve_db.", "self_healing_loop.", "roi_calculator."):
        text = text.replace(module, "")
    return text.replace("NoneType", "None")


def render_schema_table(model: Type[BaseModel]) -> str:
    """Render one model as a Markdown field table."""
    lines = [f"#### `{model.__name__}`", "", "| Field | Type | Required |", "| --- | --- | --- |"]
    for name, field in model.model_fields.items():
        required = "yes" if field.is_required() else "no"
        lines.append(f"| `{name}` | `{_field_type_str(field)}` | {required} |")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Mermaid diagrams (derived from live code where possible)
# ---------------------------------------------------------------------------

def render_pipeline_flowchart() -> str:
    """
    System overview flowchart. The stage chain is derived from the event-bus
    ``Topic`` enum ordering, so adding a topic updates the diagram.
    """
    stages = [t.value for t in Topic]  # declared order == pipeline lifecycle
    stage_nodes = "\n".join(f'    E{i}["{s}"]' for i, s in enumerate(stages))
    stage_edges = "\n".join(f"    E{i} --> E{i + 1}" for i in range(len(stages) - 1))
    return f"""```mermaid
flowchart LR
    subgraph Client["Client"]
        FE["Frontend / demo.sh"]
    end
    subgraph ORCH["Orchestrator (FastAPI, JWT-secured)"]
        API["/api/v1/modernize"]
        BUS["master_event_bus<br/>asyncio.Queue pub/sub"]
        subgraph EVENTS["Pipeline topics (from Topic enum)"]
{stage_nodes}
{stage_edges}
        end
    end
    subgraph EXT["External / mock-fallback services"]
        AUD["Auditor :8001<br/>taint + churn"]
        CVE["vector_cve_db<br/>FAISS / hashing RAG"]
        BOB["IBM Bob agent<br/>CLI or simulation"]
        SBX["Sandbox :8002<br/>test runner"]
    end
    FE -->|"POST + Bearer JWT"| API
    API --> BUS
    BUS --> AUD
    BUS --> CVE
    BUS --> BOB
    BUS --> SBX
    AUD -->|"findings"| BUS
    BOB -->|"patch"| AST["ast_mutation_engine<br/>safety + Big-O gate"]
    AST -->|"gated patch"| BUS
```"""


def render_consensus_diagram() -> str:
    """Multi-agent debate diagram, driven by the live PERSONAS registry."""
    persona_nodes = "\n".join(
        f'    P{i}["{p.name.value}<br/>weight {p.weight}"]' for i, p in enumerate(PERSONAS)
    )
    persona_edges = "\n".join(f"    PATCH --> P{i}\n    P{i} --> SCORE" for i in range(len(PERSONAS)))
    return f"""```mermaid
flowchart TD
    PATCH["IBM Bob refactored patch"] 
{persona_nodes}
    SCORE["calculate_consensus<br/>weighted mean"]
    VETO{{"security score<br/>>= veto threshold?"}}
    APPROVE["CONSENSUS_REACHED<br/>approved=true"]
    REJECT["rejected_consensus<br/>patch discarded"]
{persona_edges}
    SCORE --> VETO
    VETO -->|"yes + score >= 0.70"| APPROVE
    VETO -->|"no"| REJECT
    APPROVE --> HEAL["self_healing_loop<br/>sandbox retries x5"]
    HEAL -->|"passed"| DONE["TESTS_PASSED"]
    HEAL -->|"exhausted"| FAIL["TESTS_FAILED"]
```"""


# ---------------------------------------------------------------------------
# Subsystem registry
# ---------------------------------------------------------------------------

SUBSYSTEMS: List[Dict[str, str]] = [
    {"module": "main.py", "role": "FastAPI front door; HTTP <-> event bus; JWT-secured master route; SSE streaming"},
    {"module": "master_event_bus.py", "role": "asyncio.Queue pub/sub router; fan-out, backpressure, race-free drain"},
    {"module": "vector_cve_db.py", "role": "In-memory CVE vector DB; sentence-transformers/FAISS with hashing fallback"},
    {"module": "multi_agent_consensus.py", "role": "3-persona debate; weighted consensus + security veto"},
    {"module": "ast_mutation_engine.py", "role": "AST gate: dangerous-builtin blocklist + loop-depth Big-O guard"},
    {"module": "self_healing_loop.py", "role": "Sandbox retry loop; traceback parsing; exponential backoff"},
    {"module": "roi_calculator.py", "role": "Hours / dollars / CO2e business-value model; auditable assumptions"},
    {"module": "observability_exporter.py", "role": "Prometheus Counter/Histogram/Gauge + /metrics scrape endpoint"},
    {"module": "cross_language_parser.py", "role": "Polyglot scanning: Python AST + JS/TS/Java security rules"},
    {"module": "enterprise_auth.py", "role": "OAuth2 password grant + HS256 JWT (jose or stdlib HMAC)"},
    {"module": "chaos_monkey_tester.py", "role": "Fault-injection suite proving graceful degradation"},
]


# ---------------------------------------------------------------------------
# Document assembly
# ---------------------------------------------------------------------------

def generate_markdown() -> str:
    """Compile the full ARCHITECTURE.md content."""
    routes = collect_routes()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    route_rows = "\n".join(
        f"| `{r['path']}` | {r['methods']} | {r['auth']} | `{r['response']}` |"
        for r in routes
    )

    schema_sections = "\n".join(
        f"### {group}\n\n" + "\n".join(render_schema_table(m) for m in models)
        for group, models in SCHEMA_REGISTRY.items()
    )

    subsystem_rows = "\n".join(f"| `{s['module']}` | {s['role']} |" for s in SUBSYSTEMS)

    return f"""{GENERATED_BANNER}

# Architecture — Automated Enterprise Legacy & Security Modernizer

*Generated {now} by `auto_doc_generator.py` from live code introspection.*

## System overview

{render_pipeline_flowchart()}

## Multi-agent consensus loop

Every IBM Bob patch must survive a weighted debate before it can ship. The
Security Expert holds a veto that no average can overrule.

{render_consensus_diagram()}

## Event bus topics (pipeline lifecycle)

| # | Topic | Meaning |
| --- | --- | --- |
{chr(10).join(f"| {i} | `{t.name}` (`{t.value}`) | stage of the modernization pipeline |" for i, t in enumerate(Topic))}

## API surface (read live from `main.app`)

| Path | Methods | Auth | Response model |
| --- | --- | --- | --- |
{route_rows}

## Subsystem registry

| Module | Responsibility |
| --- | --- |
{subsystem_rows}

## Data schemas (read live from Pydantic models)

{schema_sections}
## Resilience

See `chaos_monkey_tester.py` — four fault-injection scenarios (Bob timeout,
AST parser crash, sandbox OOM, transport-level 500 contract) all prove the
orchestrator degrades gracefully and never hangs.
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main_cli() -> int:
    parser = argparse.ArgumentParser(description="Generate ARCHITECTURE.md from live code.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="output path (default: repo root)")
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()

    content = generate_markdown()
    out = Path(args.output)

    if args.check:
        if not out.exists():
            print(f"STALE: {out} does not exist")
            return 1
        # Ignore the timestamp line when diffing.
        strip_ts = lambda t: "\n".join(  # noqa: E731
            line for line in t.splitlines() if not line.startswith("*Generated ")
        )
        if strip_ts(out.read_text()) != strip_ts(content):
            print(f"STALE: {out} is out of date — run auto_doc_generator.py")
            return 1
        print(f"FRESH: {out} is up to date")
        return 0

    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out} ({len(content)} bytes, {len(collect_routes())} routes, "
          f"{sum(len(m) for m in SCHEMA_REGISTRY.values())} schemas)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main_cli())
